// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: v1/waffle_interface.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *RegisterReq) Reset() {
	*x = RegisterReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReq) ProtoMessage() {}

func (x *RegisterReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReq.ProtoReflect.Descriptor instead.
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RegisterReply) Reset() {
	*x = RegisterReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterReply) ProtoMessage() {}

func (x *RegisterReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterReply.ProtoReflect.Descriptor instead.
func (*RegisterReply) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *LoginReply) Reset() {
	*x = LoginReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReply) ProtoMessage() {}

func (x *LoginReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReply.ProtoReflect.Descriptor instead.
func (*LoginReply) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{3}
}

func (x *LoginReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LogoutReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{4}
}

type LogoutReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{5}
}

type PingReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{6}
}

type PingReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{7}
}

func (x *PingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRPCReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRPCReq) Reset() {
	*x = PingRPCReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRPCReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRPCReq) ProtoMessage() {}

func (x *PingRPCReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRPCReq.ProtoReflect.Descriptor instead.
func (*PingRPCReq) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{8}
}

type PingRPCReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PingRPCReply) Reset() {
	*x = PingRPCReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRPCReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRPCReply) ProtoMessage() {}

func (x *PingRPCReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRPCReply.ProtoReflect.Descriptor instead.
func (*PingRPCReply) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{9}
}

func (x *PingRPCReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GenerateUploadImgUrlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName []string `protobuf:"bytes,1,rep,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
}

func (x *GenerateUploadImgUrlReq) Reset() {
	*x = GenerateUploadImgUrlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateUploadImgUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadImgUrlReq) ProtoMessage() {}

func (x *GenerateUploadImgUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadImgUrlReq.ProtoReflect.Descriptor instead.
func (*GenerateUploadImgUrlReq) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateUploadImgUrlReq) GetImageName() []string {
	if x != nil {
		return x.ImageName
	}
	return nil
}

type GenerateUploadImgUrlReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*GenerateUploadImgUrlReply_Image `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *GenerateUploadImgUrlReply) Reset() {
	*x = GenerateUploadImgUrlReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateUploadImgUrlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadImgUrlReply) ProtoMessage() {}

func (x *GenerateUploadImgUrlReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadImgUrlReply.ProtoReflect.Descriptor instead.
func (*GenerateUploadImgUrlReply) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateUploadImgUrlReply) GetResult() []*GenerateUploadImgUrlReply_Image {
	if x != nil {
		return x.Result
	}
	return nil
}

type GenerateUploadAvatarUrlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
}

func (x *GenerateUploadAvatarUrlReq) Reset() {
	*x = GenerateUploadAvatarUrlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateUploadAvatarUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadAvatarUrlReq) ProtoMessage() {}

func (x *GenerateUploadAvatarUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadAvatarUrlReq.ProtoReflect.Descriptor instead.
func (*GenerateUploadAvatarUrlReq) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{12}
}

func (x *GenerateUploadAvatarUrlReq) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type GenerateUploadAvatarUrlReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadUrl  string `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	AvatarName string `protobuf:"bytes,2,opt,name=avatar_name,json=avatarName,proto3" json:"avatar_name,omitempty"`
	AvatarUuid string `protobuf:"bytes,3,opt,name=avatar_uuid,json=avatarUuid,proto3" json:"avatar_uuid,omitempty"`
}

func (x *GenerateUploadAvatarUrlReply) Reset() {
	*x = GenerateUploadAvatarUrlReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateUploadAvatarUrlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadAvatarUrlReply) ProtoMessage() {}

func (x *GenerateUploadAvatarUrlReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadAvatarUrlReply.ProtoReflect.Descriptor instead.
func (*GenerateUploadAvatarUrlReply) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateUploadAvatarUrlReply) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GenerateUploadAvatarUrlReply) GetAvatarName() string {
	if x != nil {
		return x.AvatarName
	}
	return ""
}

func (x *GenerateUploadAvatarUrlReply) GetAvatarUuid() string {
	if x != nil {
		return x.AvatarUuid
	}
	return ""
}

type VerifyImagesUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageInfo []*VerifyImagesUploadReq_Info `protobuf:"bytes,1,rep,name=image_info,json=imageInfo,proto3" json:"image_info,omitempty"`
}

func (x *VerifyImagesUploadReq) Reset() {
	*x = VerifyImagesUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyImagesUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyImagesUploadReq) ProtoMessage() {}

func (x *VerifyImagesUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyImagesUploadReq.ProtoReflect.Descriptor instead.
func (*VerifyImagesUploadReq) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{14}
}

func (x *VerifyImagesUploadReq) GetImageInfo() []*VerifyImagesUploadReq_Info {
	if x != nil {
		return x.ImageInfo
	}
	return nil
}

type VerifyImagesUploadReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *VerifyImagesUploadReply) Reset() {
	*x = VerifyImagesUploadReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyImagesUploadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyImagesUploadReply) ProtoMessage() {}

func (x *VerifyImagesUploadReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyImagesUploadReply.ProtoReflect.Descriptor instead.
func (*VerifyImagesUploadReply) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{15}
}

func (x *VerifyImagesUploadReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VerifyAvatarUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvatarName string `protobuf:"bytes,1,opt,name=avatar_name,json=avatarName,proto3" json:"avatar_name,omitempty"`
	AvatarUuid string `protobuf:"bytes,2,opt,name=avatar_uuid,json=avatarUuid,proto3" json:"avatar_uuid,omitempty"`
}

func (x *VerifyAvatarUploadReq) Reset() {
	*x = VerifyAvatarUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyAvatarUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAvatarUploadReq) ProtoMessage() {}

func (x *VerifyAvatarUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAvatarUploadReq.ProtoReflect.Descriptor instead.
func (*VerifyAvatarUploadReq) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{16}
}

func (x *VerifyAvatarUploadReq) GetAvatarName() string {
	if x != nil {
		return x.AvatarName
	}
	return ""
}

func (x *VerifyAvatarUploadReq) GetAvatarUuid() string {
	if x != nil {
		return x.AvatarUuid
	}
	return ""
}

type VerifyAvatarUploadReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadUrl string `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
}

func (x *VerifyAvatarUploadReply) Reset() {
	*x = VerifyAvatarUploadReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyAvatarUploadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAvatarUploadReply) ProtoMessage() {}

func (x *VerifyAvatarUploadReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAvatarUploadReply.ProtoReflect.Descriptor instead.
func (*VerifyAvatarUploadReply) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{17}
}

func (x *VerifyAvatarUploadReply) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

// image -tag
type AddImageTagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ParentName string `protobuf:"bytes,2,opt,name=parentName,proto3" json:"parentName,omitempty"`
}

func (x *AddImageTagReq) Reset() {
	*x = AddImageTagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddImageTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddImageTagReq) ProtoMessage() {}

func (x *AddImageTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddImageTagReq.ProtoReflect.Descriptor instead.
func (*AddImageTagReq) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{18}
}

func (x *AddImageTagReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddImageTagReq) GetParentName() string {
	if x != nil {
		return x.ParentName
	}
	return ""
}

type AddImageTagReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddImageTagReply) Reset() {
	*x = AddImageTagReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddImageTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddImageTagReply) ProtoMessage() {}

func (x *AddImageTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddImageTagReply.ProtoReflect.Descriptor instead.
func (*AddImageTagReply) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{19}
}

type SearchImageTagByNameLikeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SearchImageTagByNameLikeReq) Reset() {
	*x = SearchImageTagByNameLikeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchImageTagByNameLikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchImageTagByNameLikeReq) ProtoMessage() {}

func (x *SearchImageTagByNameLikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchImageTagByNameLikeReq.ProtoReflect.Descriptor instead.
func (*SearchImageTagByNameLikeReq) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{20}
}

func (x *SearchImageTagByNameLikeReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SearchImageTagByNameLikeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags []*SearchImageTagByNameLikeReply_Tags `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *SearchImageTagByNameLikeReply) Reset() {
	*x = SearchImageTagByNameLikeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchImageTagByNameLikeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchImageTagByNameLikeReply) ProtoMessage() {}

func (x *SearchImageTagByNameLikeReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchImageTagByNameLikeReply.ProtoReflect.Descriptor instead.
func (*SearchImageTagByNameLikeReply) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{21}
}

func (x *SearchImageTagByNameLikeReply) GetTags() []*SearchImageTagByNameLikeReply_Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ReloadCategoryRedisImageTagReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadCategoryRedisImageTagReq) Reset() {
	*x = ReloadCategoryRedisImageTagReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadCategoryRedisImageTagReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadCategoryRedisImageTagReq) ProtoMessage() {}

func (x *ReloadCategoryRedisImageTagReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadCategoryRedisImageTagReq.ProtoReflect.Descriptor instead.
func (*ReloadCategoryRedisImageTagReq) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{22}
}

type ReloadCategoryRedisImageTagReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReloadCategoryRedisImageTagReply) Reset() {
	*x = ReloadCategoryRedisImageTagReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadCategoryRedisImageTagReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadCategoryRedisImageTagReply) ProtoMessage() {}

func (x *ReloadCategoryRedisImageTagReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadCategoryRedisImageTagReply.ProtoReflect.Descriptor instead.
func (*ReloadCategoryRedisImageTagReply) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{23}
}

type GenerateUploadImgUrlReply_Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadUrl string `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ImageName string `protobuf:"bytes,2,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ImageUuid string `protobuf:"bytes,3,opt,name=image_uuid,json=imageUuid,proto3" json:"image_uuid,omitempty"`
}

func (x *GenerateUploadImgUrlReply_Image) Reset() {
	*x = GenerateUploadImgUrlReply_Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateUploadImgUrlReply_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadImgUrlReply_Image) ProtoMessage() {}

func (x *GenerateUploadImgUrlReply_Image) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadImgUrlReply_Image.ProtoReflect.Descriptor instead.
func (*GenerateUploadImgUrlReply_Image) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GenerateUploadImgUrlReply_Image) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *GenerateUploadImgUrlReply_Image) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *GenerateUploadImgUrlReply_Image) GetImageUuid() string {
	if x != nil {
		return x.ImageUuid
	}
	return ""
}

type VerifyImagesUploadReq_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string   `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ImageUuid string   `protobuf:"bytes,2,opt,name=image_uuid,json=imageUuid,proto3" json:"image_uuid,omitempty"`
	Category  string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Purity    string   `protobuf:"bytes,4,opt,name=purity,proto3" json:"purity,omitempty"`
	Tags      []uint64 `protobuf:"varint,5,rep,packed,name=tags,proto3" json:"tags,omitempty"`
}

func (x *VerifyImagesUploadReq_Info) Reset() {
	*x = VerifyImagesUploadReq_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyImagesUploadReq_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyImagesUploadReq_Info) ProtoMessage() {}

func (x *VerifyImagesUploadReq_Info) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyImagesUploadReq_Info.ProtoReflect.Descriptor instead.
func (*VerifyImagesUploadReq_Info) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{14, 0}
}

func (x *VerifyImagesUploadReq_Info) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *VerifyImagesUploadReq_Info) GetImageUuid() string {
	if x != nil {
		return x.ImageUuid
	}
	return ""
}

func (x *VerifyImagesUploadReq_Info) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *VerifyImagesUploadReq_Info) GetPurity() string {
	if x != nil {
		return x.Purity
	}
	return ""
}

func (x *VerifyImagesUploadReq_Info) GetTags() []uint64 {
	if x != nil {
		return x.Tags
	}
	return nil
}

type SearchImageTagByNameLikeReply_Tags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id   int64  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SearchImageTagByNameLikeReply_Tags) Reset() {
	*x = SearchImageTagByNameLikeReply_Tags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_waffle_interface_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchImageTagByNameLikeReply_Tags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchImageTagByNameLikeReply_Tags) ProtoMessage() {}

func (x *SearchImageTagByNameLikeReply_Tags) ProtoReflect() protoreflect.Message {
	mi := &file_v1_waffle_interface_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchImageTagByNameLikeReply_Tags.ProtoReflect.Descriptor instead.
func (*SearchImageTagByNameLikeReply_Tags) Descriptor() ([]byte, []int) {
	return file_v1_waffle_interface_proto_rawDescGZIP(), []int{21, 0}
}

func (x *SearchImageTagByNameLikeReply_Tags) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchImageTagByNameLikeReply_Tags) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_v1_waffle_interface_proto protoreflect.FileDescriptor

var file_v1_waffle_interface_proto_rawDesc = []byte{
	0x0a, 0x19, 0x76, 0x31, 0x2f, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x5f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x77, 0x61, 0x66,
	0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45,
	0x0a, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x1f, 0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x42, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x22, 0x0a, 0x0a, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x0b,
	0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x22, 0x0d, 0x0a, 0x0b, 0x4c,
	0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x09, 0x0a, 0x07, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x71, 0x22, 0x25, 0x0a, 0x09, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0c, 0x0a, 0x0a,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x22, 0x28, 0x0a, 0x0c, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x50, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x38, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x12,
	0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xcf,
	0x01, 0x0a, 0x19, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4c, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x77,
	0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x64, 0x0a, 0x05, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55,
	0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x75, 0x69, 0x64,
	0x22, 0x3b, 0x0a, 0x1a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x1d,
	0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7f, 0x0a,
	0x1c, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a,
	0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0xf6,
	0x01, 0x0a, 0x15, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x4e, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x77,
	0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x8c, 0x01, 0x0a, 0x04, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x75, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70,
	0x75, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x04, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x33, 0x0a, 0x17, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x59, 0x0a, 0x15,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x5f, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x55, 0x75, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x17, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x72,
	0x6c, 0x22, 0x44, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67,
	0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x31, 0x0a, 0x1b, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x42, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x98,
	0x01, 0x0a, 0x1d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61,
	0x67, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x4b, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x37,
	0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x54, 0x61, 0x67, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x2e, 0x54, 0x61, 0x67, 0x73, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x1a, 0x2a, 0x0a,
	0x04, 0x54, 0x61, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x20, 0x0a, 0x1e, 0x52, 0x65, 0x6c,
	0x6f, 0x61, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x64, 0x69, 0x73,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x22, 0x22, 0x0a, 0x20, 0x52,
	0x65, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x64,
	0x69, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32,
	0xc7, 0x0c, 0x0a, 0x0f, 0x57, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66,
	0x61, 0x63, 0x65, 0x12, 0x69, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x20, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x22, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x3a, 0x01, 0x2a,
	0x22, 0x0c, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x5d,
	0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1d, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x3a,
	0x01, 0x2a, 0x22, 0x09, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x61, 0x0a,
	0x06, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x12, 0x1e, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f,
	0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x6f,
	0x67, 0x6f, 0x75, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0f, 0x3a, 0x01, 0x2a, 0x22, 0x0a, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74,
	0x12, 0x59, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c,
	0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x1e, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x3a, 0x01,
	0x2a, 0x22, 0x08, 0x2f, 0x76, 0x31, 0x2f, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x65, 0x0a, 0x07, 0x50,
	0x69, 0x6e, 0x67, 0x52, 0x50, 0x43, 0x12, 0x1f, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65,
	0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x50, 0x43, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x10, 0x3a, 0x01, 0x2a, 0x22, 0x0b, 0x2f, 0x76, 0x31, 0x2f, 0x50, 0x69, 0x6e, 0x67, 0x52,
	0x50, 0x43, 0x12, 0x99, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x12, 0x2c, 0x2e, 0x77, 0x61,
	0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x2e, 0x2e, 0x77, 0x61, 0x66, 0x66,
	0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d,
	0x67, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x23, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x1d, 0x3a, 0x01, 0x2a, 0x22, 0x18, 0x2f, 0x76, 0x31, 0x2f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x12, 0xa5,
	0x01, 0x0a, 0x17, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x2f, 0x2e, 0x77, 0x61, 0x66,
	0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x31, 0x2e, 0x77, 0x61,
	0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x26,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x20, 0x3a, 0x01, 0x2a, 0x22, 0x1b, 0x2f, 0x76, 0x31, 0x2f, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x91, 0x01, 0x0a, 0x12, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2a, 0x2e,
	0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x2c, 0x2e, 0x77, 0x61, 0x66, 0x66,
	0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x3a,
	0x01, 0x2a, 0x22, 0x16, 0x2f, 0x76, 0x31, 0x2f, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x91, 0x01, 0x0a, 0x12, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x12, 0x2a, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x2c, 0x2e,
	0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x21, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1b, 0x3a, 0x01, 0x2a, 0x22, 0x16, 0x2f, 0x76, 0x31, 0x2f, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x75,
	0x0a, 0x0b, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x12, 0x23, 0x2e,
	0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x52,
	0x65, 0x71, 0x1a, 0x25, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x14, 0x3a, 0x01, 0x2a, 0x22, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x41, 0x64, 0x64, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x54, 0x61, 0x67, 0x12, 0xa9, 0x01, 0x0a, 0x18, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69,
	0x6b, 0x65, 0x12, 0x30, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x6b,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x32, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x4c,
	0x69, 0x6b, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x27, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x21,
	0x3a, 0x01, 0x2a, 0x22, 0x1c, 0x2f, 0x76, 0x31, 0x2f, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x4c, 0x69, 0x6b,
	0x65, 0x12, 0xb5, 0x01, 0x0a, 0x1b, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x64, 0x69, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61,
	0x67, 0x12, 0x33, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6c, 0x6f, 0x61, 0x64, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x64, 0x69, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x54, 0x61, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x35, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x6c,
	0x6f, 0x61, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x64, 0x69, 0x73,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2a, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x24, 0x3a, 0x01, 0x2a, 0x22, 0x1f, 0x2f, 0x76, 0x31, 0x2f, 0x52, 0x65,
	0x6c, 0x6f, 0x61, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x64, 0x69,
	0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x54, 0x61, 0x67, 0x42, 0x1c, 0x5a, 0x1a, 0x61, 0x70, 0x69,
	0x2f, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_waffle_interface_proto_rawDescOnce sync.Once
	file_v1_waffle_interface_proto_rawDescData = file_v1_waffle_interface_proto_rawDesc
)

func file_v1_waffle_interface_proto_rawDescGZIP() []byte {
	file_v1_waffle_interface_proto_rawDescOnce.Do(func() {
		file_v1_waffle_interface_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_waffle_interface_proto_rawDescData)
	})
	return file_v1_waffle_interface_proto_rawDescData
}

var file_v1_waffle_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_v1_waffle_interface_proto_goTypes = []any{
	(*RegisterReq)(nil),                        // 0: waffle.interface.v1.RegisterReq
	(*RegisterReply)(nil),                      // 1: waffle.interface.v1.RegisterReply
	(*LoginReq)(nil),                           // 2: waffle.interface.v1.LoginReq
	(*LoginReply)(nil),                         // 3: waffle.interface.v1.LoginReply
	(*LogoutReq)(nil),                          // 4: waffle.interface.v1.LogoutReq
	(*LogoutReply)(nil),                        // 5: waffle.interface.v1.LogoutReply
	(*PingReq)(nil),                            // 6: waffle.interface.v1.PingReq
	(*PingReply)(nil),                          // 7: waffle.interface.v1.PingReply
	(*PingRPCReq)(nil),                         // 8: waffle.interface.v1.PingRPCReq
	(*PingRPCReply)(nil),                       // 9: waffle.interface.v1.PingRPCReply
	(*GenerateUploadImgUrlReq)(nil),            // 10: waffle.interface.v1.GenerateUploadImgUrlReq
	(*GenerateUploadImgUrlReply)(nil),          // 11: waffle.interface.v1.GenerateUploadImgUrlReply
	(*GenerateUploadAvatarUrlReq)(nil),         // 12: waffle.interface.v1.GenerateUploadAvatarUrlReq
	(*GenerateUploadAvatarUrlReply)(nil),       // 13: waffle.interface.v1.GenerateUploadAvatarUrlReply
	(*VerifyImagesUploadReq)(nil),              // 14: waffle.interface.v1.VerifyImagesUploadReq
	(*VerifyImagesUploadReply)(nil),            // 15: waffle.interface.v1.VerifyImagesUploadReply
	(*VerifyAvatarUploadReq)(nil),              // 16: waffle.interface.v1.VerifyAvatarUploadReq
	(*VerifyAvatarUploadReply)(nil),            // 17: waffle.interface.v1.VerifyAvatarUploadReply
	(*AddImageTagReq)(nil),                     // 18: waffle.interface.v1.AddImageTagReq
	(*AddImageTagReply)(nil),                   // 19: waffle.interface.v1.AddImageTagReply
	(*SearchImageTagByNameLikeReq)(nil),        // 20: waffle.interface.v1.SearchImageTagByNameLikeReq
	(*SearchImageTagByNameLikeReply)(nil),      // 21: waffle.interface.v1.SearchImageTagByNameLikeReply
	(*ReloadCategoryRedisImageTagReq)(nil),     // 22: waffle.interface.v1.ReloadCategoryRedisImageTagReq
	(*ReloadCategoryRedisImageTagReply)(nil),   // 23: waffle.interface.v1.ReloadCategoryRedisImageTagReply
	(*GenerateUploadImgUrlReply_Image)(nil),    // 24: waffle.interface.v1.GenerateUploadImgUrlReply.Image
	(*VerifyImagesUploadReq_Info)(nil),         // 25: waffle.interface.v1.VerifyImagesUploadReq.Info
	(*SearchImageTagByNameLikeReply_Tags)(nil), // 26: waffle.interface.v1.SearchImageTagByNameLikeReply.Tags
}
var file_v1_waffle_interface_proto_depIdxs = []int32{
	24, // 0: waffle.interface.v1.GenerateUploadImgUrlReply.result:type_name -> waffle.interface.v1.GenerateUploadImgUrlReply.Image
	25, // 1: waffle.interface.v1.VerifyImagesUploadReq.image_info:type_name -> waffle.interface.v1.VerifyImagesUploadReq.Info
	26, // 2: waffle.interface.v1.SearchImageTagByNameLikeReply.tags:type_name -> waffle.interface.v1.SearchImageTagByNameLikeReply.Tags
	0,  // 3: waffle.interface.v1.WaffleInterface.Register:input_type -> waffle.interface.v1.RegisterReq
	2,  // 4: waffle.interface.v1.WaffleInterface.Login:input_type -> waffle.interface.v1.LoginReq
	4,  // 5: waffle.interface.v1.WaffleInterface.Logout:input_type -> waffle.interface.v1.LogoutReq
	6,  // 6: waffle.interface.v1.WaffleInterface.Ping:input_type -> waffle.interface.v1.PingReq
	8,  // 7: waffle.interface.v1.WaffleInterface.PingRPC:input_type -> waffle.interface.v1.PingRPCReq
	10, // 8: waffle.interface.v1.WaffleInterface.GenerateUploadImgUrl:input_type -> waffle.interface.v1.GenerateUploadImgUrlReq
	12, // 9: waffle.interface.v1.WaffleInterface.GenerateUploadAvatarUrl:input_type -> waffle.interface.v1.GenerateUploadAvatarUrlReq
	14, // 10: waffle.interface.v1.WaffleInterface.VerifyImagesUpload:input_type -> waffle.interface.v1.VerifyImagesUploadReq
	16, // 11: waffle.interface.v1.WaffleInterface.VerifyAvatarUpload:input_type -> waffle.interface.v1.VerifyAvatarUploadReq
	18, // 12: waffle.interface.v1.WaffleInterface.AddImageTag:input_type -> waffle.interface.v1.AddImageTagReq
	20, // 13: waffle.interface.v1.WaffleInterface.SearchImageTagByNameLike:input_type -> waffle.interface.v1.SearchImageTagByNameLikeReq
	22, // 14: waffle.interface.v1.WaffleInterface.ReloadCategoryRedisImageTag:input_type -> waffle.interface.v1.ReloadCategoryRedisImageTagReq
	1,  // 15: waffle.interface.v1.WaffleInterface.Register:output_type -> waffle.interface.v1.RegisterReply
	3,  // 16: waffle.interface.v1.WaffleInterface.Login:output_type -> waffle.interface.v1.LoginReply
	5,  // 17: waffle.interface.v1.WaffleInterface.Logout:output_type -> waffle.interface.v1.LogoutReply
	7,  // 18: waffle.interface.v1.WaffleInterface.Ping:output_type -> waffle.interface.v1.PingReply
	9,  // 19: waffle.interface.v1.WaffleInterface.PingRPC:output_type -> waffle.interface.v1.PingRPCReply
	11, // 20: waffle.interface.v1.WaffleInterface.GenerateUploadImgUrl:output_type -> waffle.interface.v1.GenerateUploadImgUrlReply
	13, // 21: waffle.interface.v1.WaffleInterface.GenerateUploadAvatarUrl:output_type -> waffle.interface.v1.GenerateUploadAvatarUrlReply
	15, // 22: waffle.interface.v1.WaffleInterface.VerifyImagesUpload:output_type -> waffle.interface.v1.VerifyImagesUploadReply
	17, // 23: waffle.interface.v1.WaffleInterface.VerifyAvatarUpload:output_type -> waffle.interface.v1.VerifyAvatarUploadReply
	19, // 24: waffle.interface.v1.WaffleInterface.AddImageTag:output_type -> waffle.interface.v1.AddImageTagReply
	21, // 25: waffle.interface.v1.WaffleInterface.SearchImageTagByNameLike:output_type -> waffle.interface.v1.SearchImageTagByNameLikeReply
	23, // 26: waffle.interface.v1.WaffleInterface.ReloadCategoryRedisImageTag:output_type -> waffle.interface.v1.ReloadCategoryRedisImageTagReply
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_v1_waffle_interface_proto_init() }
func file_v1_waffle_interface_proto_init() {
	if File_v1_waffle_interface_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_waffle_interface_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*LoginReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*LogoutReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LogoutReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PingReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*PingReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*PingRPCReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*PingRPCReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateUploadImgUrlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateUploadImgUrlReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateUploadAvatarUrlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateUploadAvatarUrlReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyImagesUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyImagesUploadReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyAvatarUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyAvatarUploadReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*AddImageTagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*AddImageTagReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*SearchImageTagByNameLikeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*SearchImageTagByNameLikeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*ReloadCategoryRedisImageTagReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*ReloadCategoryRedisImageTagReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*GenerateUploadImgUrlReply_Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyImagesUploadReq_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_waffle_interface_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*SearchImageTagByNameLikeReply_Tags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_waffle_interface_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_waffle_interface_proto_goTypes,
		DependencyIndexes: file_v1_waffle_interface_proto_depIdxs,
		MessageInfos:      file_v1_waffle_interface_proto_msgTypes,
	}.Build()
	File_v1_waffle_interface_proto = out.File
	file_v1_waffle_interface_proto_rawDesc = nil
	file_v1_waffle_interface_proto_goTypes = nil
	file_v1_waffle_interface_proto_depIdxs = nil
}
