server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 5s
data:
  database:
    driver: mysql
    source: root:Becterium@3@tcp(192.168.37.134:3306)/waffle?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 192.168.37.134:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  key: some-secret-key