// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: v1/media.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadImagesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName []string `protobuf:"bytes,1,rep,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
}

func (x *UploadImagesReq) Reset() {
	*x = UploadImagesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImagesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImagesReq) ProtoMessage() {}

func (x *UploadImagesReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImagesReq.ProtoReflect.Descriptor instead.
func (*UploadImagesReq) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *UploadImagesReq) GetImageName() []string {
	if x != nil {
		return x.ImageName
	}
	return nil
}

type UploadImagesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*UploadImagesReply_Image `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
}

func (x *UploadImagesReply) Reset() {
	*x = UploadImagesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImagesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImagesReply) ProtoMessage() {}

func (x *UploadImagesReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImagesReply.ProtoReflect.Descriptor instead.
func (*UploadImagesReply) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadImagesReply) GetResult() []*UploadImagesReply_Image {
	if x != nil {
		return x.Result
	}
	return nil
}

type UploadUserImageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
}

func (x *UploadUserImageReq) Reset() {
	*x = UploadUserImageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadUserImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadUserImageReq) ProtoMessage() {}

func (x *UploadUserImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadUserImageReq.ProtoReflect.Descriptor instead.
func (*UploadUserImageReq) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{2}
}

func (x *UploadUserImageReq) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type UploadUserImageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvatarUrl  string `protobuf:"bytes,1,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	AvatarName string `protobuf:"bytes,2,opt,name=avatar_name,json=avatarName,proto3" json:"avatar_name,omitempty"`
	AvatarUuid string `protobuf:"bytes,3,opt,name=avatar_uuid,json=avatarUuid,proto3" json:"avatar_uuid,omitempty"`
}

func (x *UploadUserImageReply) Reset() {
	*x = UploadUserImageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadUserImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadUserImageReply) ProtoMessage() {}

func (x *UploadUserImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadUserImageReply.ProtoReflect.Descriptor instead.
func (*UploadUserImageReply) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{3}
}

func (x *UploadUserImageReply) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UploadUserImageReply) GetAvatarName() string {
	if x != nil {
		return x.AvatarName
	}
	return ""
}

func (x *UploadUserImageReply) GetAvatarUuid() string {
	if x != nil {
		return x.AvatarUuid
	}
	return ""
}

type VerifyUserImageUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
}

func (x *VerifyUserImageUploadReq) Reset() {
	*x = VerifyUserImageUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyUserImageUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserImageUploadReq) ProtoMessage() {}

func (x *VerifyUserImageUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserImageUploadReq.ProtoReflect.Descriptor instead.
func (*VerifyUserImageUploadReq) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyUserImageUploadReq) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type VerifyUserImageUploadReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AvatarUrl string `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
}

func (x *VerifyUserImageUploadReply) Reset() {
	*x = VerifyUserImageUploadReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyUserImageUploadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserImageUploadReply) ProtoMessage() {}

func (x *VerifyUserImageUploadReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserImageUploadReply.ProtoReflect.Descriptor instead.
func (*VerifyUserImageUploadReply) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyUserImageUploadReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyUserImageUploadReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VerifyUserImageUploadReply) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

type VerifyImagesUploadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageInfo []*VerifyImagesUploadReq_Info `protobuf:"bytes,1,rep,name=image_info,json=imageInfo,proto3" json:"image_info,omitempty"`
}

func (x *VerifyImagesUploadReq) Reset() {
	*x = VerifyImagesUploadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyImagesUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyImagesUploadReq) ProtoMessage() {}

func (x *VerifyImagesUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyImagesUploadReq.ProtoReflect.Descriptor instead.
func (*VerifyImagesUploadReq) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{6}
}

func (x *VerifyImagesUploadReq) GetImageInfo() []*VerifyImagesUploadReq_Info {
	if x != nil {
		return x.ImageInfo
	}
	return nil
}

type VerifyImagesUploadReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *VerifyImagesUploadReply) Reset() {
	*x = VerifyImagesUploadReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyImagesUploadReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyImagesUploadReply) ProtoMessage() {}

func (x *VerifyImagesUploadReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyImagesUploadReply.ProtoReflect.Descriptor instead.
func (*VerifyImagesUploadReply) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyImagesUploadReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyImagesUploadReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetImageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageUrl string `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *GetImageReq) Reset() {
	*x = GetImageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageReq) ProtoMessage() {}

func (x *GetImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageReq.ProtoReflect.Descriptor instead.
func (*GetImageReq) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{8}
}

func (x *GetImageReq) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type GetImageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags      []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Uploader  string   `protobuf:"bytes,2,opt,name=uploader,proto3" json:"uploader,omitempty"` //user URL
	Category  string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Purity    string   `protobuf:"bytes,4,opt,name=purity,proto3" json:"purity,omitempty"`
	Size      int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Views     int64    `protobuf:"varint,6,opt,name=views,proto3" json:"views,omitempty"`
	Favorites int64    `protobuf:"varint,7,opt,name=favorites,proto3" json:"favorites,omitempty"`
	Link      string   `protobuf:"bytes,8,opt,name=link,proto3" json:"link,omitempty"`           //image_URL
	Thumbnail string   `protobuf:"bytes,9,opt,name=Thumbnail,proto3" json:"Thumbnail,omitempty"` //image_UUID
}

func (x *GetImageReply) Reset() {
	*x = GetImageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageReply) ProtoMessage() {}

func (x *GetImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageReply.ProtoReflect.Descriptor instead.
func (*GetImageReply) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{9}
}

func (x *GetImageReply) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetImageReply) GetUploader() string {
	if x != nil {
		return x.Uploader
	}
	return ""
}

func (x *GetImageReply) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetImageReply) GetPurity() string {
	if x != nil {
		return x.Purity
	}
	return ""
}

func (x *GetImageReply) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetImageReply) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *GetImageReply) GetFavorites() int64 {
	if x != nil {
		return x.Favorites
	}
	return 0
}

func (x *GetImageReply) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *GetImageReply) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

type UpLoadVideoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoName string `protobuf:"bytes,1,opt,name=video_name,json=videoName,proto3" json:"video_name,omitempty"`
	VideoData []byte `protobuf:"bytes,2,opt,name=video_data,json=videoData,proto3" json:"video_data,omitempty"`
	VideoType string `protobuf:"bytes,3,opt,name=video_type,json=videoType,proto3" json:"video_type,omitempty"`
}

func (x *UpLoadVideoReq) Reset() {
	*x = UpLoadVideoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpLoadVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpLoadVideoReq) ProtoMessage() {}

func (x *UpLoadVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpLoadVideoReq.ProtoReflect.Descriptor instead.
func (*UpLoadVideoReq) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{10}
}

func (x *UpLoadVideoReq) GetVideoName() string {
	if x != nil {
		return x.VideoName
	}
	return ""
}

func (x *UpLoadVideoReq) GetVideoData() []byte {
	if x != nil {
		return x.VideoData
	}
	return nil
}

func (x *UpLoadVideoReq) GetVideoType() string {
	if x != nil {
		return x.VideoType
	}
	return ""
}

type UpLoadVideoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url     string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpLoadVideoReply) Reset() {
	*x = UpLoadVideoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpLoadVideoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpLoadVideoReply) ProtoMessage() {}

func (x *UpLoadVideoReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpLoadVideoReply.ProtoReflect.Descriptor instead.
func (*UpLoadVideoReply) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{11}
}

func (x *UpLoadVideoReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpLoadVideoReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpLoadVideoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// todo: Need to define
type GetVideoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVideoReq) Reset() {
	*x = GetVideoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoReq) ProtoMessage() {}

func (x *GetVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoReq.ProtoReflect.Descriptor instead.
func (*GetVideoReq) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{12}
}

type GetVideoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVideoReply) Reset() {
	*x = GetVideoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoReply) ProtoMessage() {}

func (x *GetVideoReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoReply.ProtoReflect.Descriptor instead.
func (*GetVideoReply) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{13}
}

type UploadImagesReply_Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadUrl string `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ImageName string `protobuf:"bytes,2,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ImageUuid string `protobuf:"bytes,3,opt,name=image_uuid,json=imageUuid,proto3" json:"image_uuid,omitempty"`
}

func (x *UploadImagesReply_Image) Reset() {
	*x = UploadImagesReply_Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImagesReply_Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImagesReply_Image) ProtoMessage() {}

func (x *UploadImagesReply_Image) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImagesReply_Image.ProtoReflect.Descriptor instead.
func (*UploadImagesReply_Image) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{1, 0}
}

func (x *UploadImagesReply_Image) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *UploadImagesReply_Image) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *UploadImagesReply_Image) GetImageUuid() string {
	if x != nil {
		return x.ImageUuid
	}
	return ""
}

type VerifyImagesUploadReq_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageName string   `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	ImageUuid string   `protobuf:"bytes,2,opt,name=image_uuid,json=imageUuid,proto3" json:"image_uuid,omitempty"`
	Category  string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Purity    string   `protobuf:"bytes,4,opt,name=purity,proto3" json:"purity,omitempty"`
	Tags      []uint64 `protobuf:"varint,5,rep,packed,name=tags,proto3" json:"tags,omitempty"`
}

func (x *VerifyImagesUploadReq_Info) Reset() {
	*x = VerifyImagesUploadReq_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyImagesUploadReq_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyImagesUploadReq_Info) ProtoMessage() {}

func (x *VerifyImagesUploadReq_Info) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyImagesUploadReq_Info.ProtoReflect.Descriptor instead.
func (*VerifyImagesUploadReq_Info) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{6, 0}
}

func (x *VerifyImagesUploadReq_Info) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *VerifyImagesUploadReq_Info) GetImageUuid() string {
	if x != nil {
		return x.ImageUuid
	}
	return ""
}

func (x *VerifyImagesUploadReq_Info) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *VerifyImagesUploadReq_Info) GetPurity() string {
	if x != nil {
		return x.Purity
	}
	return ""
}

func (x *VerifyImagesUploadReq_Info) GetTags() []uint64 {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_v1_media_proto protoreflect.FileDescriptor

var file_v1_media_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x0f, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xb5, 0x01, 0x0a, 0x11,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x3a, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x1a, 0x64, 0x0a,
	0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55,
	0x75, 0x69, 0x64, 0x22, 0x33, 0x0a, 0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x77, 0x0a, 0x14, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12,
	0x1f, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x75, 0x69,
	0x64, 0x22, 0x39, 0x0a, 0x18, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a,
	0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x6f, 0x0a, 0x1a,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x22, 0xec, 0x01,
	0x0a, 0x15, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x44, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x77, 0x61,
	0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x2e, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x8c, 0x01,
	0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x55, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x75, 0x72, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x04, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x22, 0x4d, 0x0a, 0x17,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0xed, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x72, 0x69, 0x74, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x72, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x76, 0x69, 0x65, 0x77, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x61, 0x76, 0x6f, 0x72,
	0x69, 0x74, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x66, 0x61, 0x76, 0x6f,
	0x72, 0x69, 0x74, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x68, 0x75,
	0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x68,
	0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x22, 0x6d, 0x0a, 0x0e, 0x55, 0x70, 0x4c, 0x6f, 0x61,
	0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76,
	0x69, 0x64, 0x65, 0x6f, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x64, 0x65,
	0x6f, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x76, 0x69,
	0x64, 0x65, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x69, 0x64,
	0x65, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x22, 0x58, 0x0a, 0x10, 0x55, 0x70, 0x4c, 0x6f, 0x61, 0x64,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x22,
	0x0f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x32, 0xb6, 0x04, 0x0a, 0x05, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x4a, 0x0a, 0x0c, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1a, 0x2e, 0x77, 0x61, 0x66,
	0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x73, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0f, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x2e, 0x77, 0x61, 0x66, 0x66,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x1f, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x65, 0x0a, 0x15, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x23, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x77, 0x61, 0x66, 0x66,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x5c, 0x0a, 0x12, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x20, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x77, 0x61, 0x66,
	0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x73, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x3e, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x16, 0x2e, 0x77,
	0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x47, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12,
	0x19, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x4c, 0x6f,
	0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x77, 0x61, 0x66,
	0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x4c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x16, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x42, 0x0a, 0x17, 0x64, 0x65, 0x76,
	0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x56, 0x31, 0x50, 0x01, 0x5a, 0x17, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_media_proto_rawDescOnce sync.Once
	file_v1_media_proto_rawDescData = file_v1_media_proto_rawDesc
)

func file_v1_media_proto_rawDescGZIP() []byte {
	file_v1_media_proto_rawDescOnce.Do(func() {
		file_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_media_proto_rawDescData)
	})
	return file_v1_media_proto_rawDescData
}

var file_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_v1_media_proto_goTypes = []any{
	(*UploadImagesReq)(nil),            // 0: waffle.v1.UploadImagesReq
	(*UploadImagesReply)(nil),          // 1: waffle.v1.UploadImagesReply
	(*UploadUserImageReq)(nil),         // 2: waffle.v1.UploadUserImageReq
	(*UploadUserImageReply)(nil),       // 3: waffle.v1.UploadUserImageReply
	(*VerifyUserImageUploadReq)(nil),   // 4: waffle.v1.VerifyUserImageUploadReq
	(*VerifyUserImageUploadReply)(nil), // 5: waffle.v1.VerifyUserImageUploadReply
	(*VerifyImagesUploadReq)(nil),      // 6: waffle.v1.VerifyImagesUploadReq
	(*VerifyImagesUploadReply)(nil),    // 7: waffle.v1.VerifyImagesUploadReply
	(*GetImageReq)(nil),                // 8: waffle.v1.GetImageReq
	(*GetImageReply)(nil),              // 9: waffle.v1.GetImageReply
	(*UpLoadVideoReq)(nil),             // 10: waffle.v1.UpLoadVideoReq
	(*UpLoadVideoReply)(nil),           // 11: waffle.v1.UpLoadVideoReply
	(*GetVideoReq)(nil),                // 12: waffle.v1.GetVideoReq
	(*GetVideoReply)(nil),              // 13: waffle.v1.GetVideoReply
	(*UploadImagesReply_Image)(nil),    // 14: waffle.v1.UploadImagesReply.Image
	(*VerifyImagesUploadReq_Info)(nil), // 15: waffle.v1.VerifyImagesUploadReq.Info
}
var file_v1_media_proto_depIdxs = []int32{
	14, // 0: waffle.v1.UploadImagesReply.result:type_name -> waffle.v1.UploadImagesReply.Image
	15, // 1: waffle.v1.VerifyImagesUploadReq.image_info:type_name -> waffle.v1.VerifyImagesUploadReq.Info
	0,  // 2: waffle.v1.Media.UploadImages:input_type -> waffle.v1.UploadImagesReq
	2,  // 3: waffle.v1.Media.UploadUserImage:input_type -> waffle.v1.UploadUserImageReq
	4,  // 4: waffle.v1.Media.VerifyUserImageUpload:input_type -> waffle.v1.VerifyUserImageUploadReq
	6,  // 5: waffle.v1.Media.VerifyImagesUpload:input_type -> waffle.v1.VerifyImagesUploadReq
	8,  // 6: waffle.v1.Media.GetImage:input_type -> waffle.v1.GetImageReq
	10, // 7: waffle.v1.Media.UploadVideo:input_type -> waffle.v1.UpLoadVideoReq
	12, // 8: waffle.v1.Media.GetVideo:input_type -> waffle.v1.GetVideoReq
	1,  // 9: waffle.v1.Media.UploadImages:output_type -> waffle.v1.UploadImagesReply
	3,  // 10: waffle.v1.Media.UploadUserImage:output_type -> waffle.v1.UploadUserImageReply
	5,  // 11: waffle.v1.Media.VerifyUserImageUpload:output_type -> waffle.v1.VerifyUserImageUploadReply
	7,  // 12: waffle.v1.Media.VerifyImagesUpload:output_type -> waffle.v1.VerifyImagesUploadReply
	9,  // 13: waffle.v1.Media.GetImage:output_type -> waffle.v1.GetImageReply
	11, // 14: waffle.v1.Media.UploadVideo:output_type -> waffle.v1.UpLoadVideoReply
	13, // 15: waffle.v1.Media.GetVideo:output_type -> waffle.v1.GetVideoReply
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_v1_media_proto_init() }
func file_v1_media_proto_init() {
	if File_v1_media_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_media_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UploadImagesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UploadImagesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UploadUserImageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UploadUserImageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyUserImageUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyUserImageUploadReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyImagesUploadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyImagesUploadReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetImageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetImageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*UpLoadVideoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*UpLoadVideoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*GetVideoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*GetVideoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*UploadImagesReply_Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyImagesUploadReq_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_media_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_media_proto_goTypes,
		DependencyIndexes: file_v1_media_proto_depIdxs,
		MessageInfos:      file_v1_media_proto_msgTypes,
	}.Build()
	File_v1_media_proto = out.File
	file_v1_media_proto_rawDesc = nil
	file_v1_media_proto_goTypes = nil
	file_v1_media_proto_depIdxs = nil
}
