// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: v1/media.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadImageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string  `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Purity   string  `protobuf:"bytes,2,opt,name=purity,proto3" json:"purity,omitempty"`
	Tags     []int64 `protobuf:"varint,3,rep,packed,name=tags,proto3" json:"tags,omitempty"`
}

func (x *UploadImageReq) Reset() {
	*x = UploadImageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageReq) ProtoMessage() {}

func (x *UploadImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageReq.ProtoReflect.Descriptor instead.
func (*UploadImageReq) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *UploadImageReq) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UploadImageReq) GetPurity() string {
	if x != nil {
		return x.Purity
	}
	return ""
}

func (x *UploadImageReq) GetTags() []int64 {
	if x != nil {
		return x.Tags
	}
	return nil
}

type UploadImageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadUrl string `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	ImageUrl  string `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *UploadImageReply) Reset() {
	*x = UploadImageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageReply) ProtoMessage() {}

func (x *UploadImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageReply.ProtoReflect.Descriptor instead.
func (*UploadImageReply) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadImageReply) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *UploadImageReply) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type VerifyUploadImageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageUrl string `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *VerifyUploadImageReq) Reset() {
	*x = VerifyUploadImageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyUploadImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUploadImageReq) ProtoMessage() {}

func (x *VerifyUploadImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUploadImageReq.ProtoReflect.Descriptor instead.
func (*VerifyUploadImageReq) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyUploadImageReq) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type VerifyUploadImageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *VerifyUploadImageReply) Reset() {
	*x = VerifyUploadImageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyUploadImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUploadImageReply) ProtoMessage() {}

func (x *VerifyUploadImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUploadImageReply.ProtoReflect.Descriptor instead.
func (*VerifyUploadImageReply) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyUploadImageReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VerifyUploadImageReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetImageReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImageUrl string `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
}

func (x *GetImageReq) Reset() {
	*x = GetImageReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageReq) ProtoMessage() {}

func (x *GetImageReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageReq.ProtoReflect.Descriptor instead.
func (*GetImageReq) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{4}
}

func (x *GetImageReq) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type GetImageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags      []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	Uploader  string   `protobuf:"bytes,2,opt,name=uploader,proto3" json:"uploader,omitempty"` //user URL
	Category  string   `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Purity    string   `protobuf:"bytes,4,opt,name=purity,proto3" json:"purity,omitempty"`
	Size      int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Views     int64    `protobuf:"varint,6,opt,name=views,proto3" json:"views,omitempty"`
	Favorites int64    `protobuf:"varint,7,opt,name=favorites,proto3" json:"favorites,omitempty"`
	Link      string   `protobuf:"bytes,8,opt,name=link,proto3" json:"link,omitempty"`           //image_URL
	Thumbnail string   `protobuf:"bytes,9,opt,name=Thumbnail,proto3" json:"Thumbnail,omitempty"` //image_UUID
}

func (x *GetImageReply) Reset() {
	*x = GetImageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetImageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageReply) ProtoMessage() {}

func (x *GetImageReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageReply.ProtoReflect.Descriptor instead.
func (*GetImageReply) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{5}
}

func (x *GetImageReply) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetImageReply) GetUploader() string {
	if x != nil {
		return x.Uploader
	}
	return ""
}

func (x *GetImageReply) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetImageReply) GetPurity() string {
	if x != nil {
		return x.Purity
	}
	return ""
}

func (x *GetImageReply) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetImageReply) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *GetImageReply) GetFavorites() int64 {
	if x != nil {
		return x.Favorites
	}
	return 0
}

func (x *GetImageReply) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *GetImageReply) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

type UpLoadVideoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VideoName string `protobuf:"bytes,1,opt,name=video_name,json=videoName,proto3" json:"video_name,omitempty"`
	VideoData []byte `protobuf:"bytes,2,opt,name=video_data,json=videoData,proto3" json:"video_data,omitempty"`
	VideoType string `protobuf:"bytes,3,opt,name=video_type,json=videoType,proto3" json:"video_type,omitempty"`
}

func (x *UpLoadVideoReq) Reset() {
	*x = UpLoadVideoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpLoadVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpLoadVideoReq) ProtoMessage() {}

func (x *UpLoadVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpLoadVideoReq.ProtoReflect.Descriptor instead.
func (*UpLoadVideoReq) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{6}
}

func (x *UpLoadVideoReq) GetVideoName() string {
	if x != nil {
		return x.VideoName
	}
	return ""
}

func (x *UpLoadVideoReq) GetVideoData() []byte {
	if x != nil {
		return x.VideoData
	}
	return nil
}

func (x *UpLoadVideoReq) GetVideoType() string {
	if x != nil {
		return x.VideoType
	}
	return ""
}

type UpLoadVideoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url     string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpLoadVideoReply) Reset() {
	*x = UpLoadVideoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpLoadVideoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpLoadVideoReply) ProtoMessage() {}

func (x *UpLoadVideoReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpLoadVideoReply.ProtoReflect.Descriptor instead.
func (*UpLoadVideoReply) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{7}
}

func (x *UpLoadVideoReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UpLoadVideoReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpLoadVideoReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// todo: Need to define
type GetVideoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVideoReq) Reset() {
	*x = GetVideoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoReq) ProtoMessage() {}

func (x *GetVideoReq) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoReq.ProtoReflect.Descriptor instead.
func (*GetVideoReq) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{8}
}

type GetVideoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVideoReply) Reset() {
	*x = GetVideoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_media_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVideoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVideoReply) ProtoMessage() {}

func (x *GetVideoReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_media_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVideoReply.ProtoReflect.Descriptor instead.
func (*GetVideoReply) Descriptor() ([]byte, []int) {
	return file_v1_media_proto_rawDescGZIP(), []int{9}
}

var File_v1_media_proto protoreflect.FileDescriptor

var file_v1_media_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x58, 0x0a, 0x0e, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x72, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x72, 0x69, 0x74, 0x79, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x22, 0x4e, 0x0a, 0x10, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x55, 0x72, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x55, 0x72, 0x6c, 0x22, 0x33, 0x0a, 0x14, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x4c, 0x0a, 0x16, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55,
	0x72, 0x6c, 0x22, 0xed, 0x01, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x75, 0x72, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x75, 0x72, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x69, 0x65, 0x77, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x69, 0x65,
	0x77, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x66, 0x61, 0x76, 0x6f, 0x72, 0x69, 0x74, 0x65, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69,
	0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61,
	0x69, 0x6c, 0x22, 0x6d, 0x0a, 0x0e, 0x55, 0x70, 0x4c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65,
	0x6f, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x58, 0x0a, 0x10, 0x55, 0x70, 0x4c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x47,
	0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x0f, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xf4, 0x02, 0x0a, 0x05,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x47, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x19, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x1b, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x59,
	0x0a, 0x11, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d,
	0x61, 0x67, 0x65, 0x12, 0x1f, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x16, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e,
	0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0b, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x19, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x4c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f,
	0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x4c, 0x6f, 0x61, 0x64, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x3e, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x12, 0x16,
	0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69,
	0x64, 0x65, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x42, 0x42, 0x0a, 0x17, 0x64, 0x65, 0x76, 0x2e, 0x77, 0x61, 0x66, 0x66, 0x6c, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x76, 0x31, 0x42, 0x0c, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x56, 0x31, 0x50, 0x01, 0x5a, 0x17, 0x61,
	0x70, 0x69, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_media_proto_rawDescOnce sync.Once
	file_v1_media_proto_rawDescData = file_v1_media_proto_rawDesc
)

func file_v1_media_proto_rawDescGZIP() []byte {
	file_v1_media_proto_rawDescOnce.Do(func() {
		file_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_media_proto_rawDescData)
	})
	return file_v1_media_proto_rawDescData
}

var file_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_v1_media_proto_goTypes = []any{
	(*UploadImageReq)(nil),         // 0: waffle.v1.UploadImageReq
	(*UploadImageReply)(nil),       // 1: waffle.v1.UploadImageReply
	(*VerifyUploadImageReq)(nil),   // 2: waffle.v1.VerifyUploadImageReq
	(*VerifyUploadImageReply)(nil), // 3: waffle.v1.VerifyUploadImageReply
	(*GetImageReq)(nil),            // 4: waffle.v1.GetImageReq
	(*GetImageReply)(nil),          // 5: waffle.v1.GetImageReply
	(*UpLoadVideoReq)(nil),         // 6: waffle.v1.UpLoadVideoReq
	(*UpLoadVideoReply)(nil),       // 7: waffle.v1.UpLoadVideoReply
	(*GetVideoReq)(nil),            // 8: waffle.v1.GetVideoReq
	(*GetVideoReply)(nil),          // 9: waffle.v1.GetVideoReply
}
var file_v1_media_proto_depIdxs = []int32{
	0, // 0: waffle.v1.Media.UploadImage:input_type -> waffle.v1.UploadImageReq
	2, // 1: waffle.v1.Media.VerifyUploadImage:input_type -> waffle.v1.VerifyUploadImageReq
	4, // 2: waffle.v1.Media.GetImage:input_type -> waffle.v1.GetImageReq
	6, // 3: waffle.v1.Media.UploadVideo:input_type -> waffle.v1.UpLoadVideoReq
	8, // 4: waffle.v1.Media.GetVideo:input_type -> waffle.v1.GetVideoReq
	1, // 5: waffle.v1.Media.UploadImage:output_type -> waffle.v1.UploadImageReply
	3, // 6: waffle.v1.Media.VerifyUploadImage:output_type -> waffle.v1.VerifyUploadImageReply
	5, // 7: waffle.v1.Media.GetImage:output_type -> waffle.v1.GetImageReply
	7, // 8: waffle.v1.Media.UploadVideo:output_type -> waffle.v1.UpLoadVideoReply
	9, // 9: waffle.v1.Media.GetVideo:output_type -> waffle.v1.GetVideoReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_media_proto_init() }
func file_v1_media_proto_init() {
	if File_v1_media_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_media_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UploadImageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*UploadImageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyUploadImageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyUploadImageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetImageReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetImageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpLoadVideoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*UpLoadVideoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetVideoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_media_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetVideoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_media_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_media_proto_goTypes,
		DependencyIndexes: file_v1_media_proto_depIdxs,
		MessageInfos:      file_v1_media_proto_msgTypes,
	}.Build()
	File_v1_media_proto = out.File
	file_v1_media_proto_rawDesc = nil
	file_v1_media_proto_goTypes = nil
	file_v1_media_proto_depIdxs = nil
}
