// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"waffle/app/media/service/internal/biz"
	"waffle/app/media/service/internal/conf"
	"waffle/app/media/service/internal/data"
	"waffle/app/media/service/internal/server"
	"waffle/app/media/service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func initApp(confServer *conf.Server, logger log.Logger) (*kratos.App, func(), error) {

}
