// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"waffle/app/media/service/internal/biz"
	"waffle/app/media/service/internal/conf"
	"waffle/app/media/service/internal/data"
	"waffle/app/media/service/internal/server"
	"waffle/app/media/service/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func initApp(confServer *conf.Server, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(logger)
	if err != nil {
		return nil, nil, err
	}
	mediaRepo := data.NewMediaRepo(dataData, logger)
	mediaUseCase := biz.NewMediaUseCase(mediaRepo, logger)
	mediaService := service.NewMediaService(mediaUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, mediaService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
