// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"waffle/app/waffle/interface/internal/biz"
	"waffle/app/waffle/interface/internal/conf"
	"waffle/app/waffle/interface/internal/data"
	"waffle/app/waffle/interface/internal/server"
	"waffle/app/waffle/interface/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	userClient := data.NewUserServiceClient(auth, discovery)
	dataData, err := data.NewData(confData, userClient, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	userUseCase := biz.NewUserUseCase(auth, userRepo, logger)
	waffleInterface := service.NewWaffleInterface(logger, userUseCase)
	grpcServer := server.NewGRPCServer(confServer, auth, waffleInterface, logger)
	httpServer := server.NewHTTPServer(confServer, auth, waffleInterface, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
	}, nil
}
