server:
  http:
    addr: 0.0.0.0:8000
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 5s
  kafka:
    addrs:
      - 192.168.37.134:9094


minio:
    client:
      endpoint : "192.168.37.100:30000"
      key_id : "9kvM1l0d0R7xhZMcfb9K"
      access_key : "4ji0Be6Jptu7PoWeV8to1HTUP9zVbpFZTsSrMKd4"
data:
  database:
    driver: mysql
    source: root:Becterium@3@tcp(192.168.37.134:3306)/waffle?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 192.168.37.134:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  elasticsearch:
    addr: http://192.168.37.100:30002

auth:
  key: some-secret-key