server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
minio:
    client:
      endpoint : "192.168.37.100:30000"
      key_id : "rkcle3LXkm80SWdK2Rni"
      access_key : "v4Glp37kR3tJGDKTsPUCdzxAmGURgXwY3GkFASth"
auth:
  key: some-secret-key