server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
  kafka:
    broker:
      addr: 192.168.37.134:9094
    topic: "image"

minio:
    client:
      endpoint : "192.168.37.100:30000"
      key_id : "Ecr5leJ27JhQTPgsXFV1"
      access_key : "OuScJDks4d16FYUjBg5NzsM0UCCnwtsjrNAeUjxc"
data:
  database:
    driver: mysql
    source: root:Becterium@3@tcp(192.168.37.134:3306)/waffle?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 192.168.37.134:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  elasticsearch:
    addr: http://192.168.37.100:30002

auth:
  key: some-secret-key