server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
minio:
    client:
      endpoint : "192.168.37.100:30000"
      key_id : "rkcle3LXkm80SWdK2Rni"
      access_key : "v4Glp37kR3tJGDKTsPUCdzxAmGURgXwY3GkFASth"
data:
  database:
    driver: mysql
    source: root:Becterium@3@tcp(127.0.0.1:3306)/waffle?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 192.168.37.134:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
auth:
  key: some-secret-key