apiVersion: v1
kind: Namespace
metadata:
  name: waffle
  labels:
    name: waffle
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: media-waffle
  name: media-waffle
  namespace: waffle
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media-waffle
  template:
    metadata:
      labels:
        app: media-waffle
    spec:
      containers:
        - name: media-waffle
          image: 192.168.37.130:8009/library/waffle/media-kratos:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: media-waffle-config-volume
              mountPath: /data/conf
      restartPolicy: Always
      volumes:
        - name: media-waffle-config-volume
          configMap:
            name: media-waffle-config