apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: devops
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - port: 6379
      name: redis
      nodePort: 30379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: devops
spec:
  serviceName: redis
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: 192.168.37.130:8009/library/redis:7.4.0
          ports:
            - containerPort: 6379
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              if [ "$(hostname)" = "redis-0" ]; then
                redis-server --port 6379 --protected-mode no --replica-announce-ip redis-0.redis.devops.svc.cluster.local
              else
                redis-server --port 6379 --protected-mode no --replicaof redis-0.redis.devops.svc.cluster.local 6379 --replica-announce-ip $(hostname).redis.devops.svc.cluster.local
              fi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      containers:
        - name: redis-sentinel
          image: 192.168.37.130:8009/library/redis:7.4.0
          ports:
            - containerPort: 26379
          command: [ "/bin/sh" ]
          args:
            - "-c"
            - |
              cp /etc/redis/sentinel.conf /tmp/sentinel.conf && \
              redis-sentinel /tmp/sentinel.conf
          volumeMounts:
            - name: sentinel-conf
              mountPath: /etc/redis
      volumes:
        - name: sentinel-conf
          configMap:
            name: sentinel-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-config
  namespace: devops
data:
  sentinel.conf: |
    port 26379
    sentinel monitor mymaster redis-0.redis.devops.svc.cluster.local 6379 2
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 60000
    sentinel parallel-syncs mymaster 1
    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes