version: '3.8'

services:
  redis:
    image: 192.168.37.130:8009/library/redis:7.4.0
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - /data/redis/conf/redis.conf:/etc/redis/redis.conf
      - /data/redis/data:/data
    command: ["redis-server", "/etc/redis/redis.conf"]
